print("hello world")
print("Ben is wearing a blue shirt. I like it.")
print("I like to run.")
print("I asked Ben if he wanted to go running. He responded: \"no way\"")
print("\t its weird he does not like to run")
